### ISSUE TITLE
Requires metatag module?

### ISSUE THREAD

**Issue by jacobSingh** [colophonemes/drupal-to-markdown#1]
When I ran the script, I got this:

`Error: ER_NO_SUCH_TABLE: Table 'jacobsingh_dev.metatag' doesn't exist`

**Comment by colophonemes** [comment]
Hey, I'm not maintaining this any more, but if you comment out lines 291-307 in `run.js` it should fix it.

https://github.com/colophonemes/drupal-to-markdown/blob/master/run.js#L291
